version: '3'
services:
  app:
    build: . 
    container_name: projectopia-frontend-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    environment:
      API_URL: http://localhost:8000/api
      PORT: 8000